### ISSUE TITLE
bqr_delete_table gives jason related error

### ISSUE THREAD

**Issue by DavidArenburg** [cloudyr/bigQueryR#12]
```r
### Using some arbitrary names
bqr_delete_table("My_Project", "My_data_set", "My_table")

Request Status Code: 204
Error: parse error: premature EOF
                                       
                     (right here) ------^

```

Tested this with the `bigrquery::delete_table` on the same data set and it works perfectly

This error also appears with `bqr_upload_data(...., overwrite = TRUE)` obviously as it runs `bqr_delete_table` too underneath.

**Comment by MarkEdmondson1234** [comment]
Thanks for the report, this used to work so I've broken it somehow, will take a look :)

**Comment by MarkEdmondson1234** [comment]
It does delete the table, it just raises an error when it does so as it returns a 204 error that googleAuthR didn't class as a success.  

This is now changed from 0.3.0.9000 of googleAuthR so installing that from github should remove this error message.  Thanks!
