### ISSUE TITLE
Standard SQL queries

### ISSUE THREAD

**Issue by ks--ks** [cloudyr/bigQueryR#21]
Starting earlier this year Big Query supports a new version of SQL dialect https://cloud.google.com/bigquery/sql-reference/

 bigQueryR currently supports only legacy version. Please add support of the new version of SQL

**Comment by MarkEdmondson1234** [comment]
Looks doable, will probably have a flag in the request of "old" verses "new"

**Comment by ks--ks** [comment]
Thanks! Looking forward to try it!

**Comment by MarkEdmondson1234** [comment]
@ks--ks Ok its in now for `bqr_query`function, could you test it out?

**Comment by MarkEdmondson1234** [comment]
@ks--ks did you get a chance to test this out?

**Comment by tophcito** [comment]
In case you still look for feedback on this issue, I just got around testing standard SQL with bqr_query and it works like a charm. Thanks for implementing this!

**Comment by MarkEdmondson1234** [comment]
@tophcito Great thanks :)  I'll close this issue then.
