### ISSUE TITLE
Error attempt to apply a non function bgr_query

### ISSUE THREAD

**Issue by liveaffiliates** [cloudyr/bigQueryR#22]
Hi,

Thanks for making this awesome library it seems like the only way to connect R with Shiny, the effort you have put in is appreciated.

I am trying to do a simple Query with it and it is failing (this might just be my lack of knowledge with R).

It returning list of projects and data sets correctly so I know it is connected.

I followed the guides on querying:
	
`"bqr_query(projectId, datasetId, query, maxResults = 1000)"`

This is the command I put in:

`result <- bqr_query("bigqyerytestproject2", "TestDataSet1", "SELECT * FROM TestTable3", maxResults = 1000)`

and I get the error:

```
Error : attempt to apply non-function
Warning message:
In q(the_body = body, path_arguments = list(projects = projectId)) :
  API Data failed to parse.  Returning parsed from JSON content.
                    Use this to test against your data_parse_function.
```

But then I checked BigQuery and the query is going through successfully:

I am just connecting a small amount before I move a large data set but the results are:
[
  {
    "Name": "Season",
    "Date": "2010-06-30",
    "ID": "1"
  },
  {
    "Name": "Test",
    "Date": "2010-06-30",
    "ID": "2"
  }
]

Thanks for your help

**Comment by MarkEdmondson1234** [comment]
I'm just now looking at this librayr again so good timing ;) 

That error comes up if its failed to parse it into a data.frame, so the query will succeed but then the results don't pop out nicely.  Do you have anything in the argument "result" ?

**Comment by MarkEdmondson1234** [comment]
This may be this issue https://github.com/cloudyr/bigQueryR/issues/5 - is it a one row result?

**Comment by liveaffiliates** [comment]
Hi Mark,
Thanks for the quick response!

The result variable says NULL(empty)  

I also saw that issue 5 may be a problem so I changed the table to have two rows.

My data came into the table from a csv like this:
Season,2010-06-30,1
Test,2010-06-30,2

and is stored in BigQuery with the schema Name: String, Date: date, ID integer. 

Regards
Nicholas

**Comment by liveaffiliates** [comment]
Hi Mark,

This is my session info:

R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bigrquery_0.3.0 bigQueryR_0.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7                 magrittr_1.5           googleCloudStorageR_0.2.0     devtools_1.12.0          
 [5] xtable_1.8-2                R6_2.2.0                  httr_1.2.1                                   dplyr_0.5.0              
 [9] tools_3.3.2                  DBI_0.5-1                googleAuthR_0.4.0                    withr_1.0.2              
[13] htmltools_0.3.5          openssl_0.9.5          digest_0.6.10                             assertthat_0.1           
[17] tibble_1.2                  crayon_1.3.2            shiny_0.14.1                               testthat_1.0.2           
[21] curl_2.2                      memoise_1.0.0        mime_0.5                                   jsonlite_1.1             
[25] httpuv_1.3.3             

This is my schema copied and pasted from BigQuery:

Name	STRING	NULLABLE	
Date	        DATE	NULLABLE	
ID	       INTEGER	NULLABLE	


This is the table details copied:

Table ID	bigqyerytestproject2:TestDataSet1.TestTable3
Table Size	46 B
Number of Rows	2
Creation Time	Nov 2, 2016, 6:47:56 PM
Last Modified	Nov 2, 2016, 6:47:56 PM
Data Location	US

And the contents copied:

Row	    Name	    Date	          ID	 
1	    Season	    2010-06-30	  1 
2	    Test	    2010-06-30	  2 

Thanks again for your help

**Comment by liveaffiliates** [comment]
I am not sure if this help but I got this error when using bigrquery Error: Don't know how to convert type date. I saw that you used some of this library in yours.

**Comment by MarkEdmondson1234** [comment]
I think thats the problem - your table uses `TIMESTAMP` but mine uses `DATE`

```
Name 	STRING 	NULLABLE 	
Describe this field...
Date 	TIMESTAMP 	NULLABLE 	
Describe this field...
ID 	FLOAT 	NULLABLE 	
Describe this field...
```

If you upload using bigQueryR it will make sure its in a type it recognises, but if you upload a dataset yourself it looks like `DATE` is unsupported.  I guess if you alter your BQ schema to `TIMESTAMP` instead of `DATE` it will work. 

I will look at adding support though, as this should work.

**Comment by liveaffiliates** [comment]
Ok yes thanks! just confirmed that I was able to replace type date with type string and it works fine. Appreciate the help.

**Comment by MarkEdmondson1234** [comment]
`DATE` looks to be deprecated and for legacy SQL only according to this:
https://cloud.google.com/bigquery/data-types

..but I added a `date = as.Date` that may work.
