### ISSUE TITLE
Authorization issue with Service Account

### ISSUE THREAD

**Issue by CurtisGreenland** [cloudyr/bigQueryR#30]
@MarkEdmondson1234 I am working some BigQuery API calls using this package. I love how the package works. And I am successful working with the package when authenticating with my own credentials using httr. However, I am struggling with getting authorization using a service account to work.

I get a Insufficient Permission error for all functions within the package after authenticating with googleAuthR. I am using:
gar_auth_service('\\file path\\xxx.json')

This is the error I get when I run any function, even the bqr_list_projects():
Request Status Code: 403
Error in checkGoogleAPIError(req) : 
  JSON fetch error: Insufficient Permission

I have validated that permissions for the service account are set correctly. In this case I have set the service account to have the highest (Owner/Admin) permission.
![image](https://cloud.githubusercontent.com/assets/8622307/23035559/24281838-f445-11e6-8fdb-7fccd800b9cc.png)

I have no issues using the service account with other packages of yours.

Here is my sessionInfo():

R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleAuthR_0.4.0.9000 bigQueryR_0.2.0       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9               googleCloudStorageR_0.2.0 digest_0.6.12             crayon_1.3.2              withr_1.0.2              
 [6] mime_0.5                  R6_2.2.0                  jsonlite_1.2              xtable_1.8-2              magrittr_1.5             
[11] httr_1.2.1                curl_2.3                  testthat_1.0.2            devtools_1.12.0           tools_3.3.2              
[16] shiny_1.0.0               httpuv_1.3.3              memoise_1.0.0             htmltools_0.3.5           openssl_0.9.6

**Comment by MarkEdmondson1234** [comment]
@CurtisGreenland just eliminating the possibility, are you sure you have the cloud platform API switched on for your project?

**Comment by MarkEdmondson1234** [comment]
Other than that, this is the reference for all user roles https://cloud.google.com/bigquery/docs/access-control

List projects may not be the best to test with as its a higher level, try at least listing tables. 

You can also turn on the option `options(googleAuthR.verbose = 2)` to see more feedback that may help.

**Comment by MarkEdmondson1234** [comment]
It may also be easiest to add the service email via the "Share dataset" button in BigQuery console
 
<img width="583" alt="screen shot 2017-02-16 at 20 48 10" src="https://cloud.githubusercontent.com/assets/3155884/23038168/5704debe-f489-11e6-845c-79c351188712.png">

**Comment by CurtisGreenland** [comment]
@MarkEdmondson1234 I have Cloud platform API turned on, I have set permission for the service account to be project owner, I have manually shared the dataset with the service account email in the BigQuery console. I have tried listing at every level and get the same permissions error.  Turning `options(googleAuthR.verbose = 2)` on provides the following:

> bqr_list_tables(projectId = project, datasetId = dataset)
Token exists.
Request: https://www.googleapis.com/bigquery/v2/projects/xxxxxxxx/datasets/xxxxxxxx/tables/
Request Status Code: 403
JSON fetch error: Insufficient Permission
No retry attempted: Insufficient Permission
Error in checkGoogleAPIError(req) : 
  JSON fetch error: Insufficient Permission

![image](https://cloud.githubusercontent.com/assets/8622307/23222596/0e53054c-f8ee-11e6-913e-713999d1a32f.png)

**Comment by MarkEdmondson1234** [comment]
@CurtisGreenland this may not fix your issue, but could perhaps help:

I've added a `gar_token_info()` to googleAuthR that will show you what the current token thinks you should be authenticating against.  Set `options(googleAuthR.verbose = 2)` and then when you auth it should display, or you can rerun it yourself with `gar_token_info()`   Let me know how it goes, and put the output here if it still doesn't help.

**Comment by CurtisGreenland** [comment]
@MarkEdmondson1234 Thank you so much. Doing this helped me figure out that the issue comes to setting scope in the `gar_auth_service()`.  I automatically assumed that the default includes all scopes, but instead I see the default scopes are only Search Console, Google Analytics, Tag Manager, and URLShortener (Which I have now read in your googleAuthR documentation) .
`getOption("googleAuthR.scopes.selected")` 
[1] "https://www.googleapis.com/auth/webmasters"                      "https://www.googleapis.com/auth/analytics"                      
[3] "https://www.googleapis.com/auth/analytics.readonly"              "https://www.googleapis.com/auth/analytics.manage.users.readonly"
[5] "https://www.googleapis.com/auth/tagmanager.readonly"             "https://www.googleapis.com/auth/urlshortener"

So, if I specify the BigQuery scopes, instead of assuming they are already selected by default, the issue is resolved.
`gar_auth_service('path to file.json',scope = c("https://www.googleapis.com/auth/bigquery","https://www.googleapis.com/auth/bigquery.insertdata","https://www.googleapis.com/auth/devstorage.read_write","https://www.googleapis.com/auth/devstorage.full_control"))`

I guess I can instead set options for scope prior to authenticating like:
`options(googleAuthR.scopes.selected = c(getOption("googleAuthR.scopes.selected"), "https://www.googleapis.com/auth/bigquery", 
"https://www.googleapis.com/auth/bigquery.insertdata", "https://www.googleapis.com/auth/devstorage.read_write", "https://www.googleapis.com/auth/devstorage.full_control"))`

**Comment by MarkEdmondson1234** [comment]
Perfect :)  Its easiest to use scope `https://www.googleapis.com/auth/cloud-platform` as that will work with Cloud Storage, BigQuery and Google Compute Engine.
