### ISSUE TITLE
Query fails that works in UI

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/bigQueryR#36]
https://github.com/cloudyr/bigQueryR/issues/35

```
select tbl1.user_id as user_id from * (select user_id from flatten([project:dataset.table],key) where y >= 1) tbl1 inner join (select user_id from [project2:dataset.table]) tbl2 on tbl1.user_id = tbl2.user_id limit 10")
```

**Comment by causeyrob** [comment]
### simplified
# works
select user_id from mytbl 

# fails
select user_id from mytbl group by user_id

**Comment by MarkEdmondson1234** [comment]
Thanks, I think the fix I did for the previous parsing broke this, but I've put tests in now so should make it harder to do that!  Will sort this out tomorrow.

**Comment by MarkEdmondson1234** [comment]
@causeyrob I'm afraid I can't replicate this, I suspect its to do with the result only having one result? May I see the dimensions of the tabel that fails in R but works in UI? 

Using latest on Github these work (using a GA360 export):

```
bqr_query(query = "select fullVisitorId from [xxx:98288.ga_sessions_20170221] group by fullVisitorId limit 1")

#>                     fullVisitorId
#> 1  30824517914616942

bqr_query(query = "select fullVisitorId from [xxx:98288.ga_sessions_20170221] limit 1")
      
#>                  fullVisitorId
#> 30824517914616942
```
