### ISSUE TITLE
googleAuthR 0.6.1 breaks bigQueryR

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/bigQueryR#43]
Sad face - revert back to 0.6.0 for now or wait for fix of 0.6.2

https://github.com/MarkEdmondson1234/googleAuthR/issues/101

    devtools::install_github("MarkEdmondson1234/googleAuthR@v6.0")

**Comment by gvdr** [comment]
ps, you probably mean devtools::install_github("MarkEdmondson1234/googleAuthR@v0.6.0")

**Comment by MarkEdmondson1234** [comment]
Yes!  But it should be fixed now regardless.

**Comment by gvdr** [comment]
Installing everything from github, it is. I think I ran into an old-dependency-not-getting-updated kind of error trying to install from cran. I will try to reproduce if you still care (probably not really worth, though.)

**Comment by MarkEdmondson1234** [comment]
Ah yes, I should then update the DESCRIPTION on CRAN to googleAuthR 0.6.2

**Comment by MarkEdmondson1234** [comment]
DESCRIPTION updated https://github.com/cloudyr/bigQueryR/commit/fe12cc4cbd5a05422bf03f999aafdfde63641bc7
