### ISSUE TITLE
library(googleCloudStorageR) resets scope, thus prevents bigQueryR authentication

### ISSUE THREAD

**Issue by peteratemarsys** [cloudyr/bigQueryR#46]
When I load the `bigQueryR` package and authenticate with a _service key_, its functions work just fine with the scope set to `https://www.googleapis.com/auth/cloud-platform` (default scope). However, after loading the `googleCloudStorageR` package I'm not able to use `bigQueryR` functions anymore due the the scope being reset to `https://www.googleapis.com/auth/devstorage.full_control`.

Can you please suggest a way to explicitly set multiple scopes and then re-authenticate to be able to use both packages at the same time? Thank you

**Comment by MarkEdmondson1234** [comment]
Yep, this is covered here on the [googleAuthR website](http://code.markedmondson.me/googleAuthR/articles/google-authentication-types.html#multiple-authentication-tokens)

In summary you need to specify the scopes before authenticating with either library, the easiest may even to be load googleCloudStorage first, then bigQueryR as they both can use the `cloud-platform` scope.

**Comment by peteratemarsys** [comment]
Thank you for your prompt reply. Both of these methods worked!
