### ISSUE TITLE
Error when passing in #standardSQL

### ISSUE THREAD

**Issue by riccardopinosio** [cloudyr/bigQueryR#51]
Hello!

If I use:

`
bqr_query(query = "#standardSQL [.....]")
`

I get an error:

`
API returned: 1.336 - 1.336: No query found.
`

The query works if I don't pass in #standardSQL in the query string but if I use the parameter `useLegacySql = FALSE` in the function call instead.
Maybe the docs could be updated to say that passing in #standardSQL will break and to use the
flag instead?

Thanks a bunch for the very useful package.

**Comment by MarkEdmondson1234** [comment]
Thanks - yes I wonder why that doesn't work, maybe its just for the web UI.

**Comment by MarkEdmondson1234** [comment]
Or I could just support it perhaps, set the `useLegacySql = FALSE` flag for you.

**Comment by riccardopinosio** [comment]
Hi,

I think it should work with the API because it works for me when I use it via the python API.
It's not a super important thing as one can set the useLegacySql flag himself, I just wanted to report it just in case someone has this problem and so you're aware of it.
Setting the useLegacySql flag automatically would be a nice addition.
