### ISSUE TITLE
bqr_query() returning 404

### ISSUE THREAD

**Issue by Jatinderrmn** [cloudyr/bigQueryR#52]
Hi,
We have been using bigqueryR package in our rshiny app and things were fine.
Recently bqr_query() started returning 404 error code and we haven't been able to find the cause for the same. On our local RStudio setup it is running fine. Please if you can help in the same.
Following is the log
Request failed [404]. Retrying in 1.9 seconds...
Request Status Code: 404
Error : lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang=en>
Following is the screenshot of dashboard error

![image](https://user-images.githubusercontent.com/38922121/39540804-663f309a-4e61-11e8-801e-d33c10b4fb5b.png)

**Comment by Jatinderrmn** [comment]
Please find as requested.

![shiny](https://user-images.githubusercontent.com/38922121/39541860-9d95706a-4e64-11e8-91cc-f9bc67de8377.png)

**Comment by MarkEdmondson1234** [comment]
I have raised an issue with shinyapps.io here
https://groups.google.com/forum/#!topic/shinyapps-users/wxMxmbdJ-L8

**Comment by MarkEdmondson1234** [comment]
I don't know why still, but if you don't need the Shiny interactive login then the same queries work with `bigrquery`so you could port to that - a demo below:

```r
## original function with query your SQL 
data <- bqr_query(projectId = "suri-bq", datasetId = "suridata", query)
```
Ported to `bigrquery`:

```r
  bigrquery::set_service_token("serviceaccount.json")
  bq <- bigrquery::bq_dataset_query(
    bigrquery::bq_dataset("suri-bq", "suridata"),
    query = query,
    use_legacy_sql = TRUE
  )
  data <- bq_table_download(bq)
```

**Comment by Gibbsdavidl** [comment]
I was getting the same error.  I just updated my R version to the latest (3.5), and reinstalled everything including bigqueryR from the github repo ... and it seemed to work. Can't test it on shinyapps yet though, R 3.5 is not available yet.

**Comment by MarkEdmondson1234** [comment]
There was another report of this, it turned out that the trailing slash on the API request is now unsupported by the API, so I changed that it it works.  Weird how it only 404'd sometimes though.

So Google changed the API endpoint, thanks :)
