### ISSUE TITLE
Upload using JSON not CSV

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/bigQueryR#54]
It may be easier for schema recognition etc.

**Comment by MarkEdmondson1234** [comment]
Nest lists are in via https://github.com/cloudyr/bigQueryR/commit/b9f48bd16a36ca8b1bee047157ee47ae59268c55 - maybe use as default for data.frames too?

**Comment by dkulp2** [comment]
I'm curious why I haven't found any upload functionality in R packages that supports ORC or Parquet since these are column oriented file formats with schema - which seems to be the right fit for data frames.

**Comment by MarkEdmondson1234** [comment]
Only due to the fact I've never needed those data formats, would welcome adding it, and I think supported now if you upload to google cloud storage first.
