### ISSUE TITLE
Update website: Error in bqr_list_datasets[my_project] :    object of type 'closure' is not subsettable

### ISSUE THREAD

**Issue by izzetagoren** [cloudyr/bigQueryR#57]
I am seeing the following error:

Error in bqr_list_datasets[my_project] : 
  object of type 'closure' is not subsettable

when trying to get data from a bigquery table using:

datasets <- bqr_list_datasets[my_project]

To avoid variable scoping issues, I tried changing the variable names and including all of the suggested libraries to no avail.

**Comment by MarkEdmondson1234** [comment]
I think you need `(` not `[` - and a string to define the project you are coming from:

```r
bqr_list_datasets("my_project")
```

**Comment by izzetagoren** [comment]
datasets <- bqr_list_datasets("name_of_gcp_project")

resolved my issue. 

I got the square brackets from the example code here :
 http://code.markedmondson.me/bigQueryR/meta.html

Cheers!

**Comment by MarkEdmondson1234** [comment]
Oh dear I really need to correct that!  Thanks for pointing it out
