### ISSUE TITLE
Edit Table Labels  

### ISSUE THREAD

**Issue by jordanwebb10** [cloudyr/bigQueryR#58]
It would be helpful to be able to edit table labels through the API.

**Comment by MarkEdmondson1234** [comment]
I just added the ability to do this actually, via bqr_patch_table(). Pass it a Table() object with the labels field

**Comment by jordanwebb10** [comment]
Mark, that's great news! Thank you for your work. 

I tried it and received the following error:
'Error: API returned: Either interval partition or range partition should be specified.' 

Any idea what this is referencing to?

**Comment by MarkEdmondson1234** [comment]
I think I would need to see some code, it sounds like you are sending in more than just labels?

**Comment by MarkEdmondson1234** [comment]
Actually I found Table was setting that itself when it shouldn't have been, I corrected that so try it now with the fresh GitHub version.

**Comment by jordanwebb10** [comment]
I just reinstalled from here. 
`devtools::install_github("cloudyr/bigQueryR")`

After authenticating I ran just this. 
Label deviceid currently exsists in the table
`bigQueryR::bqr_patch_table(bigQueryR::Table(projectId = 'ctpltraw', tableId = 'OneHundredHz', datasetId = 'msoc', labels = list(deviceid = c("11111"))))`

**Comment by jordanwebb10** [comment]
It works! Awesome, thank you. Anyidea when this will be integrated into the main package?

**Comment by MarkEdmondson1234** [comment]
some time next year is my best guess :)
