### ISSUE TITLE
getting 401 unauthorized error for application with github token which was working fine before

### ISSUE THREAD

**Issue by sandeep12d3** [cloudyr/bigQueryR#73]
Hi I created a new personalized token for github and am using that in my .env.local file. It should grant access to the app to fetch users from github. But it is showing a 401 error in the console. It was working fine just a day ago. I also created a new token for this but the error is the same.

Here is the code that I am using in react:

const github = axios.create({
  baseURL: "https://api.github.com",
  timeout: 1000,
  headers: { Authorization: process.env.REACT_APP_GITHUB_TOKEN },
});

class App extends Component {
  state = {
    users: [],
    loading: false,
    alert: null,
  };

  static propTypes = {
    searchUsers: PropTypes.func.isRequired,
  };

  // async componentDidMount() {
  //   this.setState({ loading: true });
  //   const res = await axios.get(
  //     `https://api.github.com/search/users?q=${text}&client_id=${process.env.REACT_APP_GITHUB_CLIENT_ID}&client_secret=${process.env.REACT_APP_GITHUB_CLIENT_SECRET}`
  //   );

  //   this.setState({ users: res.data.items, loading: false });
  // }

  // searchUsers = async (text) => {
  //   this.setState({ loading: true });
  //   const res = await github.get(`/search/users?q=${text}`);
  //   this.setState({ users: res.data.items, loading: false });
  // };

  searchUsers = async (text) => {
    this.setState({ loading: true });

    const res = await github.get(`/search/users?q=${text}`);

    this.setState({ users: res.data.items, loading: false });
  };

  //Clear users from state

  clearUsers = () => this.setState({ users: [], loading: false });

  //Set Alert
  setAlert = (msg, type) => {
    this.setState({ alert: { msg, type } });

    setTimeout(() => this.setState({ alert: null }), 5000);
  };

  render() {
    const { users, loading } = this.state;
    return (
      <div className="App">
        <Navbar />

        <div className="conatiner">
          <Alert alert={this.state.alert} />
          <Search
            searchUsers={this.searchUsers}
            clearUsers={this.clearUsers}
            showClear={users.length > 0 ? true : false}
            setAlert={this.setAlert}
          />
          <Users loading={loading} users={users} />
        </div>
      </div>
    );
  }
}

why is this error being shown?

**Comment by MarkEdmondson1234** [comment]
Looks like this in the wrong place, nothing to do with bigQueryR
