### ISSUE TITLE
App is blocked  - bqr_auth( ) gives the following issue

### ISSUE THREAD

**Issue by anindya5** [cloudyr/bigQueryR#74]
HI,

Started trying bigQueryR for a shiny use case, and while trying to log in using bqr_auth() after giving credentials getting this

"This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access."

Do you know what is the issue here?

**Comment by MarkEdmondson1234** [comment]
The policies have tightened up around Google OAuth2 so I would need to get video permission to authorize it.  The fix is to use your own GCP client.id rather than the default one that comes with the package - see https://code.markedmondson.me/googleAuthR/reference/gar_set_client.html
